#!/bin/sh
# https://askubuntu.com/a/102091

# do nothing if it's an upgrade
[ "$1" != 'install' ] && exit 0

# if it's a first install
# LANG is a POSIX env, which may be 'ru', 'ru_RU.UTF-8', 'ru_RU.KOI8-R' etc.
if echo "$LANG" | grep -Ei "^ru_|^ru$" | grep -Eiq 'utf8|utf-8'
	then
		echo "Для создания пробы оборудования выполните:"
		echo "$ sudo hw-probe -all -upload"
	else
		echo "To make a hardware probe run:"
		echo "$ sudo hw-probe -all -upload"
fi


